[package]
name = "enum-methods"
version = "0.0.1"
authors = ["Alek Ratzloff <alekratz@gmail.com>"]
description = "Generates methods for each enum variant."

[lib]
proc-macro = true

[dependencies]
syn = "0.11"
quote = "0.3"
lazy_static = "0.2"
